simplify autoconf; make compatible with LLVM 3.x

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -617,23 +617,27 @@ build_alias
 host_alias
 target_alias
 LLVMCONFIG
+LLVMPREFIX
+LLVM_BIN
+LLVM_LIB
 CLANG
 LLVM_OPT
 LLVM_LLC
 LLVM_LINK
 MSPGCC
-LLVMPREFIX
-LLVM_BIN
-LLVM_LIB
-MSPGCCPREFIX
-MSPGCCHEADERS
-MSPSIMPREFIX
+MSPSIM
+MSPGCC_HEADERS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
 host_alias
-target_alias'
+target_alias
+LLVMPREFIX
+LLVM_BIN
+LLVM_LIB
+MSPGCC
+MSPSIM'
 
 
 # Initialize some variables set by options.
@@ -1206,9 +1210,17 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-llvm=PATH        specify path to LLVM
   --with-mspgcc=PATH      specify path to mspgcc
-  --with-mspgcc-include=PATH
-                          specify path to mspgcc headers
   --with-mspsim=PATH      specify path to mspsim
+
+Some influential environment variables:
+  LLVMPREFIX  Location of LLVM parent directory
+  LLVM_BIN    Location of LLVM binaries
+  LLVM_LIB    Location of LLVM libraries
+  MSPGCC      Location of mspgcc
+  MSPSIM      Location of mspsim
+
+Use these variables to override the choices made by `configure' or to help
+it to find libraries and programs with nonstandard names/locations.
 
 Report bugs to <ransford@cs.umass.edu>.
 _ACEOF
@@ -1642,13 +1654,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 # Check whether --with-llvm was given.
 if test "${with_llvm+set}" = set; then
-  withval=$with_llvm; LLVMPREFIX="$withval"
+  withval=$with_llvm;
 fi
 
-for ac_prog in llvm-config llvm-config-2.9
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+if test -n "$with_llvm"; then
+  # Extract the first word of "llvm-config", so it can be a program name with args.
+set dummy llvm-config; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_LLVMCONFIG+set}" = set; then
@@ -1660,7 +1671,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in ${LLVMPREFIX}/bin
+for as_dir in ${with_llvm}/bin
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -1687,23 +1698,67 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$LLVMCONFIG" && break
+else
+  # Extract the first word of "llvm-config", so it can be a program name with args.
+set dummy llvm-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_LLVMCONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $LLVMCONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_LLVMCONFIG="$LLVMCONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_LLVMCONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
 done
+done
+IFS=$as_save_IFS
 
-if [ -z "$LLVMCONFIG" ]; then
+  ;;
+esac
+fi
+LLVMCONFIG=$ac_cv_path_LLVMCONFIG
+if test -n "$LLVMCONFIG"; then
+  { echo "$as_me:$LINENO: result: $LLVMCONFIG" >&5
+echo "${ECHO_T}$LLVMCONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+
+if test -z "$LLVMCONFIG"; then
   { { echo "$as_me:$LINENO: error: llvm-config not found in your PATH; quitting." >&5
 echo "$as_me: error: llvm-config not found in your PATH; quitting." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+
+
 LLVMPREFIX=`$LLVMCONFIG --prefix`
+
+
 LLVM_BIN=`$LLVMCONFIG --bindir`
+
+
 LLVM_LIB=`$LLVMCONFIG --libdir`
 
-for ac_prog in clang
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "clang", so it can be a program name with args.
+set dummy clang; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_CLANG+set}" = set; then
@@ -1742,13 +1797,8 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$CLANG" && break
-done
-
-for ac_prog in opt
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "opt", so it can be a program name with args.
+set dummy opt; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_LLVM_OPT+set}" = set; then
@@ -1787,18 +1837,8 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$LLVM_OPT" && break
-done
-
-if [ -z "$LLVM_OPT" ]; then
-	{ { echo "$as_me:$LINENO: error: \"LLVM misconfigured (opt tool is missing)\"" >&5
-echo "$as_me: error: \"LLVM misconfigured (opt tool is missing)\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-for ac_prog in llc
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "llc", so it can be a program name with args.
+set dummy llc; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_LLVM_LLC+set}" = set; then
@@ -1837,18 +1877,8 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$LLVM_LLC" && break
-done
-
-if [ -z "$LLVM_LLC" ]; then
-	{ { echo "$as_me:$LINENO: error: \"LLVM misconfigured (llc tool is missing)\"" >&5
-echo "$as_me: error: \"LLVM misconfigured (llc tool is missing)\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-for ac_prog in llvm-link
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+# Extract the first word of "llvm-link", so it can be a program name with args.
+set dummy llvm-link; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_LLVM_LINK+set}" = set; then
@@ -1887,25 +1917,17 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$LLVM_LINK" && break
-done
 
-if [ -z "$LLVM_LINK" ]; then
-	{ { echo "$as_me:$LINENO: error: \"LLVM misconfigured (llvm-link tool is missing)\"" >&5
-echo "$as_me: error: \"LLVM misconfigured (llvm-link tool is missing)\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 
 # Check whether --with-mspgcc was given.
 if test "${with_mspgcc+set}" = set; then
-  withval=$with_mspgcc; MSPGCCPREFIX="$withval"
+  withval=$with_mspgcc;
 fi
 
-for ac_prog in msp430-gcc
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
+if test -n "$with_mspgcc"; then
+  # Extract the first word of "gcc", so it can be a program name with args.
+set dummy gcc; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
 if test "${ac_cv_path_MSPGCC+set}" = set; then
@@ -1917,7 +1939,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in ${MSPGCCPREFIX}/bin
+for as_dir in ${with_mspgcc}/bin
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -1944,27 +1966,73 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$MSPGCC" && break
+else
+  # Extract the first word of "msp430-gcc", so it can be a program name with args.
+set dummy msp430-gcc; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_MSPGCC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $MSPGCC in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_MSPGCC="$MSPGCC" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_MSPGCC="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
 done
+done
+IFS=$as_save_IFS
 
-if [ -z "$MSPGCC" ]; then
-	{ { echo "$as_me:$LINENO: error: msp430-gcc not found; use --with-mspgcc=PATH." >&5
-echo "$as_me: error: msp430-gcc not found; use --with-mspgcc=PATH." >&2;}
+  ;;
+esac
+fi
+MSPGCC=$ac_cv_path_MSPGCC
+if test -n "$MSPGCC"; then
+  { echo "$as_me:$LINENO: result: $MSPGCC" >&5
+echo "${ECHO_T}$MSPGCC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+fi
+
+if test -z "$MSPGCC"; then
+  { { echo "$as_me:$LINENO: error: mspgcc not found in your PATH; quitting." >&5
+echo "$as_me: error: mspgcc not found in your PATH; quitting." >&2;}
    { (exit 1); exit 1; }; }
 fi
-MSPGCCPREFIX=`dirname $(which $MSPGCC)`/..
-MSPGCCHEADERS="${MSPGCCPREFIX}/include"
+
+MSPGCC_HEADERS=`echo | "$MSPGCC" -v -x c -E - 2>&1 | grep /include | awk '{sub(/^ +/, ""); printf " -I%s", $0}'`
 
 
-# Check whether --with-mspgcc-include was given.
-if test "${with_mspgcc_include+set}" = set; then
-  withval=$with_mspgcc_include; MSPGCCHEADERS="$withval"
+
+# Check whether --with-mspsim was given.
+if test "${with_mspsim+set}" = set; then
+  withval=$with_mspsim;
 fi
 
-if [ -d "$MSPGCCHEADERS" ]; then
-	as_ac_File=`echo "ac_cv_file_${MSPGCCHEADERS}/in430.h" | $as_tr_sh`
-{ echo "$as_me:$LINENO: checking for ${MSPGCCHEADERS}/in430.h" >&5
-echo $ECHO_N "checking for ${MSPGCCHEADERS}/in430.h... $ECHO_C" >&6; }
+if test -n "$with_mspsim"; then
+  MSPSIM="$with_mspsim"
+else
+  MSPSIM="/opt/mementos/src/mspsim"
+fi
+
+as_ac_File=`echo "ac_cv_file_${MSPSIM}/mspsim.jar" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for ${MSPSIM}/mspsim.jar" >&5
+echo $ECHO_N "checking for ${MSPSIM}/mspsim.jar... $ECHO_C" >&6; }
 if { as_var=$as_ac_File; eval "test \"\${$as_var+set}\" = set"; }; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
@@ -1972,7 +2040,7 @@ else
   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
-if test -r "${MSPGCCHEADERS}/in430.h"; then
+if test -r "${MSPSIM}/mspsim.jar"; then
   eval "$as_ac_File=yes"
 else
   eval "$as_ac_File=no"
@@ -1984,22 +2052,9 @@ echo "${ECHO_T}$ac_res" >&6; }
 if test `eval echo '${'$as_ac_File'}'` = yes; then
   :
 else
-  { { echo "$as_me:$LINENO: error: mspgcc headers not found; use --with-mspgcc-include=PATH" >&5
-echo "$as_me: error: mspgcc headers not found; use --with-mspgcc-include=PATH" >&2;}
+  { { echo "$as_me:$LINENO: error: mspsim.jar not found in ${MSPSIM}; quitting." >&5
+echo "$as_me: error: mspsim.jar not found in ${MSPSIM}; quitting." >&2;}
    { (exit 1); exit 1; }; }
-fi
-
-	CPPFLAGS="${CPPFLAGS} -I${MSPGCCPREFIX}/include"
-else
-	{ { echo "$as_me:$LINENO: error: mspgcc headers not found; use --with-mspgcc-include=PATH." >&5
-echo "$as_me: error: mspgcc headers not found; use --with-mspgcc-include=PATH." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-# Check whether --with-mspsim was given.
-if test "${with_mspsim+set}" = set; then
-  withval=$with_mspsim; MSPSIMPREFIX="$withval"
 fi
 
 
@@ -2681,22 +2736,21 @@ build_alias!$build_alias$ac_delim
 host_alias!$host_alias$ac_delim
 target_alias!$target_alias$ac_delim
 LLVMCONFIG!$LLVMCONFIG$ac_delim
+LLVMPREFIX!$LLVMPREFIX$ac_delim
+LLVM_BIN!$LLVM_BIN$ac_delim
+LLVM_LIB!$LLVM_LIB$ac_delim
 CLANG!$CLANG$ac_delim
 LLVM_OPT!$LLVM_OPT$ac_delim
 LLVM_LLC!$LLVM_LLC$ac_delim
 LLVM_LINK!$LLVM_LINK$ac_delim
 MSPGCC!$MSPGCC$ac_delim
-LLVMPREFIX!$LLVMPREFIX$ac_delim
-LLVM_BIN!$LLVM_BIN$ac_delim
-LLVM_LIB!$LLVM_LIB$ac_delim
-MSPGCCPREFIX!$MSPGCCPREFIX$ac_delim
-MSPGCCHEADERS!$MSPGCCHEADERS$ac_delim
-MSPSIMPREFIX!$MSPSIMPREFIX$ac_delim
+MSPSIM!$MSPSIM$ac_delim
+MSPGCC_HEADERS!$MSPGCC_HEADERS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 51; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 50; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
